<header>
    <nav class="navbar">
        <ul>
            <li>
            <a href="index.php">Home</a>
            </li>
            <li>
            <a href="jobs.php">Jobs</a>
            </li>
            <li>
            <a href="about.php">AboutMe</a>
            </li>
            <li>
            <a href="apply.php">Apply</a>
            </li>
            <li>
            <a href="login.php">Login</a>
            </li>
            <li>
            <a href="enhancementphp.php">EnhancePHP</a>
            </li>

            <li>
            <a href="manage.php">Manage</a>
            </li>

            <li>
                <div id="theme-wrapper">
                    <div  id="light-mode" class="theme-dot"></div>
                    <div  id="dark-mode" class="theme-dot"></div>
                    <div class="text">Theme</div>
                </div>
            </li>
        </ul>
    </nav>   
</header>
